[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Redirecciones cómodas hacia las funciones
[[redirects]]
  from = "/api/flight"
  to = "/.netlify/functions/flight"
  status = 200

[[redirects]]
  from = "/api/watch"
  to = "/.netlify/functions/watch"
  status = 200
